# docker-compose.yml
services:
  backend:
    build:
      context: ./conduit-backend
    container_name: conduit-backend
    ports:
      - "8021:8021"
    volumes:
      - backend_static:/app/staticfiles
      - backend_media:/app/media
      - backend_db:/app/conduit
    restart: always
    environment:
      # Example uncritical env vars (add more as needed)
      DJANGO_SETTINGS_MODULE: conduit.settings
      PYTHONUNBUFFERED: 1
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    depends_on:
      - frontend

  frontend:
    build:
      context: ./conduit-frontend
    container_name: conduit-frontend
    ports:
      - "8282:8282"
    restart: always
    environment:
      # Example uncritical env vars (add more as needed)
      NODE_ENV: production

volumes:
  backend_static:
  backend_media:
  backend_db:
